import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Parallax, ParallaxLayer } from "@react-spring/parallax";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen text-center image-url1">
        <div className="m-auto">
          <h1 className="title text-white">
            LightCOM.
            <br />
            Don't Ever Wait Again.
          </h1>
        </div>
      </div>

      <div className="flex min-h-screen text-center">
        <div className="m-auto">
          <h1 className="title text-black">
            Inteligent Systems for the Future.
          </h1>
        </div>
      </div>

      <div className="flex min-h-screen text-center image-url2">
        <div className="m-auto">
          <h1 className="title text-white">
            Be Faster, Be Smarter.
          </h1>
        </div>
      </div>

      <div className="flex min-h-screen text-center">
        <div className="m-auto flex flex-col">
          <h1 className="title text-black">
            A Powerful API.
          </h1>
          <div className="flex-1">
            <Image
              src="https://raw.githubusercontent.com/kufii/CodeSnap/master/examples/monokai_fira-code.png"
              alt="API"
              width={800}
              height={600}
              className="mx-auto"
            />
          </div>
        </div>
      </div>

      <div className="flex min-h-screen text-center image-url3">
        <div className="m-auto">
          <h1 className="title text-white">
            Install Now. 
          </h1>
        </div>
      </div>

    </div>
  );
};

export default Home;
